-- -- CREATE ROLE postgres SUPERUSER;
-- -- ALTER ROLE postgres PASSWORD 'postgres';
-- -- CREATE ROLE root SUPERUSER;
-- -- ALTER ROLE root PASSWORD 'postgres';
-- -- ALTER ROLE root LOGIN;
-- ALTER ROLE postgres LOGIN;
-- -- ALTER ROLE postgres CREATEDB;
-- -- ALTER ROLE root CREATEDB;
