// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	data "github.com/romankravchuk/eldorado/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *Storage) FindByEmail(ctx context.Context, email string) (data.User, error) {
	ret := _m.Called(ctx, email)

	var r0 data.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (data.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *Storage) FindByUsername(ctx context.Context, username string) (data.User, error) {
	ret := _m.Called(ctx, username)

	var r0 data.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (data.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, u
func (_m *Storage) Save(ctx context.Context, u *data.User) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *data.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorage(t mockConstructorTestingTNewStorage) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
